#  See https://pre-commit.com for more information
#  See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        name: pre-commit-hooks/check-added-large-files
      - id: check-executables-have-shebangs
        name: pre-commit-hooks/check-executables-have-shebangs
      - id: check-json
        name: pre-commit-hooks/check-json
        exclude: ^\.vscode/launch\.json$
      - id: check-merge-conflict
        name: pre-commit-hooks/check-merge-conflict
        args: [--assume-in-merge]
      - id: check-shebang-scripts-are-executable
        name: pre-commit-hooks/check-shebang-scripts-are-executable
      - id: check-symlinks
        name: pre-commit-hooks/check-symlinks
      - id: check-toml
        name: pre-commit-hooks/check-toml
      - id: destroyed-symlinks
        name: pre-commit-hooks/destroyed-symlinks
      - id: end-of-file-fixer
        name: pre-commit-hooks/end-of-file-fixer
      - id: fix-byte-order-marker
        name: pre-commit-hooks/fix-byte-order-marker
      - id: mixed-line-ending
        name: pre-commit-hooks/mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace
        name: pre-commit-hooks/trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.21.2
    hooks:
      - id: pyupgrade
        args: [--py311-plus, --keep-runtime-typing]

  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.14
    hooks:
      - id: vulture

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
